baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Harachili's portfolio"

theme = 'risotto'

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
ignoreErrors = ["error-remote-getjson"]

[params.theme]
palette = "base16-dark"

[params.about]
title = 'Harachili'
description = 'Drinking and capturing flags | MS student in Cybersecurity @ EIT Digital - UniTn x UTwente'

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/Harachili"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/leonardo-danella-4397b5191/"


[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:leonardo.danella36@gmail.com"
